cmake_minimum_required(VERSION 3.10)

set (LUMPDK_TARGET_TRIPLET_ARCH aarch64)
set (LUMPDK_TARGET_TRIPLET_PLAT linux)
set (LUMPDK_TARGET_TRIPLET_COMPILER gcc)

set (LUMPDK_TARGET_TRIPLET ${LUMPDK_TARGET_TRIPLET_ARCH}_${LUMPDK_TARGET_TRIPLET_PLAT}_${LUMPDK_TARGET_TRIPLET_COMPILER})

set (BUILD_ARCH aarch64)
set (BUILD_OS "Ubuntu1804")